### ISSUE TITLE
models.EOF.transform doesn't work in 1.2.1

### ISSUE THREAD

**Issue by CalipsoAdara** [nicrie/xeofs#98]
**Problem with projection**
When using a fitted model to project onto new data (with different time dimensions than the data used to fit) it creates an empty array of scores. This works in version 1.1.0 but does not in 1.2.1.

**Reproducible Example **

```python
from xeofs.models import EOF
import xarray as xr

# Load data
t2m = xr.tutorial.load_dataset("air_temperature").air

# Slice data in two, to fit the model and to transform.
# Notice that the time dimension does not overlap
fit_t2m = t2m.isel(time=slice(None,300))
trans_t2m = t2m.isel(time=slice(301,500))

# Lets fit the model with 3 modes
model = EOF(n_modes=3, standardize=False)
model.fit(fit_t2m, dim='time')

# Projection to new data 
model.transform(trans_t2m,normalized=False)
# output: nan dataarray of 3x300 dims (modes x time)
...
```

**Expected behavior**
When using the 1.1.0 version the output of model.tranform is an dataarray of the projected data (not nan) with dimensions 3x199 (modes x time)

**Versions**
 - Google collab
 - `xeofs` 1.2.0
 - `numpy` 1.24.3
 - `xarray` 2023.7.0

**Bonus**
If encounter with the following error, 

```AttributeError: module 'numpy' has no attribute '_no_nep50_warning'```
install older version of numpy (1.24.3)

```
!pip uninstall numpy
!pip install numpy==1.24.3
```
Thanks for the hard work @nicrie

**Comment by nicrie** [comment]
thanks for raising this @CalipsoAdara ,  indeed the bug seems to have slipped in in the recent minor release.  I try to get out a fix soon.
